import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import CountDown from '../components/CountDown';
import Copy from '../components/Home/Copy';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container} id="page-wrap">
      <Head>
        <title>nolla.nu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CountDown />
        <h1>hejsan nollan!</h1>
        <Copy />
      </main>
    </div>
  );
};

export default Home;
