import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import ConsoleEffect from '../components/ConsoleEffect';
import CountDown from '../components/CountDown';
import FAQ from '../components/FAQ';
import Copy from '../components/Home/Copy';

const Main = styled.main`
  display: flex;
  align-items: center;
  flex-direction: column;
`;

const Home: NextPage = () => {
  return (
    <div id="page-wrap">
      <Head>
        <title>nolla.nu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <CountDown />
        <ConsoleEffect Tag="h1" string="hejsan nollan!" />
        <Copy />
        <FAQ />
      </Main>
    </div>
  );
};

export default Home;
